intercom:
  api_token: "YOUR_INTERCOM_API_TOKEN_HERE"
  base_url: "https://api.intercom.io"
  api_version: "2.8"

export:
  output_format: "markdown"
  output_dir: "exports"
  batch_size: 15
  include_metadata: true
  include_context: true

debug: false
